version: '3'

services:
  web:
    build: 
      dockerfile: Dockerfile
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - app
  app:
    build: 
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - .:/var/lib/mysql-files:bind
      - ./init:/docker-entrypoint-initdb.d
      - movie-data:/var/lib/mysql
volumes:
  movie-data: